### ISSUE TITLE
Getting entire candidate candidates list from yago

### ISSUE THREAD

**Issue by coolguy456** [yago-naga/aida#23]
Hi ,
I have been exploring Yago for a while .I want to get entire list of mention entity list through code as shown in website.Thanks in advance
![capture](https://cloud.githubusercontent.com/assets/8592554/17204118/20bf1ee6-5493-11e6-9e94-9f52b2e9164d.PNG)

**Comment by hoffart** [comment]
Hi,

have a look here: https://github.com/yago-naga/aida#hands-on-command-line-call-example

Using the LOCAL setting you will get the full ranked list of entities. If you run GRAPH, only the best entity is returned. This is due to the nature of the algorithms. However, GRAPH works better, so if you want to get the full list, accuracy will be worse.

Hope this helps

Cheers
Johannes
