### ISSUE TITLE
AIDA:--OOKBE--

### ISSUE THREAD

**Issue by pwichmann** [yago-naga/aida#27]
Many thanks for an amazing tool! It has now become the heart of my project.

When exactly does
```AIDA:--OOKBE--```
occur and what does it mean exactly?
Does it mean there was a named entity but it could not be resolved?

**Comment by hoffart** [comment]
Glad that AIDA is of help to you!

You got it right, OOKBE means that AIDA did not assign an entity to the name because it believes there is none. There are two potential reasons:

- The NER recognized the name but there is no candidate entity in the dictionary
- None of the candidates scored a high enough confidence (this is configurable)
